# Cargo deny options
[graph]
targets = [
    # Linux
    { triple = "x86_64-unknown-linux-gnu" },
    # Windows
    { triple = "x86_64-pc-windows-gnu" },
    # Mobile (Android)
    { triple = "i686-linux-android" },
    { triple = "armv7-linux-androideabi" },
    { triple = "aarch64-linux-android" },
    # Mobile (iOS)
    { triple = "aarch64-apple-ios" },
]

all-features        = false
no-default-features = false


# This section is considered when running `cargo deny check advisories`
# More documentation for the advisories section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked  = "deny"

ignore = [
    { id = "RUSTSEC-2023-0055", reason = "no safe upgrade available, hard to replace dependency of JSON-LD" },
    { id = "RUSTSEC-2023-0071", reason = "no safe upgrade available, can be avoided by not using RSA in mysql server" },
]

# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "CECILL-B",
    "ISC",
    "MIT",
    "MIT-0",
    "Unicode-DFS-2016",
    "Zlib",
    "BSL-1.0",
]
confidence-threshold = 0.8

exceptions = [
    # Allow MPL-2.0 for libraries we do not modify
    { allow = ["MPL-2.0"], name = "webpki-roots", version = "*" },
    { allow = ["MPL-2.0"], name = "resiter", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_bindgen", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_build", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_checksum_derive", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_core", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_macros", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_meta", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_testing", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_udl", version = "*" },

    # Allow OpenSSL for ring
    { allow = ["OpenSSL"], name = "ring", version = "*" },
]

[licenses.private]
ignore = true

# Clarify ring crate license (LICENSE file not properly detected)
[[licenses.clarify]]
name          = "ring"
expression    = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

# This section is considered when running `cargo deny check bans`.
# More documentation about the 'bans' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions          = "allow"
wildcards                  = "warn"
workspace-default-features = "allow"
external-default-features  = "allow"
allow                      = []
deny                       = []


# This section is considered when running `cargo deny check sources`.
# More documentation about the 'sources' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
unknown-registry = "deny"
unknown-git      = "deny"
allow-registry   = ["https://github.com/rust-lang/crates.io-index"]
private          = ["https://gitlab.procivis.ch"]
